title: Klub ZŠ Řevnice
description: >- 
  Webové stránky Klubu rodičů a přátel školy ZŠ Řevnice, z.s.
baseurl: "" 
url: "https://www.klubzsrevnice.cz/"

prihlaska: https://forms.gle/U3drc9sVUq1uaNng7
facebook: #

excerpt_separator: <!--vice-->
permalink: /aktuality/:year/:title/

plugins:
  - jekyll-feed

collections:
  people:
    output: true
    layout: people
    permalink: /lide/:name

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "people"


exclude:
  - .sass-cache/
  - .template/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

